<?xml version="1.0" encoding="utf-8"?><Database Name="ttcm" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-JCN90A4;Initial Catalog=ttcm;Integrated Security=True" SettingsObjectName="Client.Properties.Settings" SettingsPropertyName="ttcmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="Ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DiemTichLuy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ma_LoaiKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>